version: '3'
services:
  storage:
    image: minio/minio
    container_name: minio_storage
    restart: always
    environment:
      MINIO_ROOT_USER: 'minio_admin'
      MINIO_ROOT_PASSWORD: 'minio_admin'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    volumes:
      - storage:/var/lib/minio/data
    ports:
      - "9010:9000"
      - "9011:9001"
    command: server /data
  db:
    container_name: "helios_database"
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: helios_admin
      POSTGRES_PASSWORD: dummy
      POSTGRES_DB: helios
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "55432:5432"
    logging:
      driver: none
  app:
    container_name: "helios_api"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - storage
    ports:
      - "3034:3034"
    environment:
      NODE_CONFIG: '{ "database": { "host": "db", "port": 5432 }, "file_storage": { "minio": { "end_point": "storage" } } }'
volumes:
  db_data:
  storage: