export enum PlantStatus {
  ACTIVE = 'ACTIVE',
  ACTIVE_LIMITED_GENERATION = 'ACTIVE_LIMITED_GENERATION',
  ACTIVE_PARTIALLY_DISABLED_EQUIPMENT = 'ACTIVE_PARTIALLY_DISABLED_EQUIPMENT',
  INACTIVE = 'INACTIVE',
  INACTIVE_DISABLED_BY_DISPATCHER = 'INACTIVE_DISABLED_BY_DISPATCHER',
  INACTIVE_EMERGENCY_WORK = 'INACTIVE_EMERGENCY_WORK',
}
